version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  consul:
    command: agent -dev -ui -client=0.0.0.0
    ports:
      - 8520:8500
    image: consul

  jaegertracing:
    image: jaegertracing/all-in-one:1.7
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
